apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto2-application22
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RispaJoseph/argocd-app-config.git
    targetRevision: HEAD
    path: mosquitto2
  destination: 
    server: https://kubernetes.default.svc
    namespace: mosquitto2

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  
  


  




