apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"mongodb","app.kubernetes.io/instance":"mongodb-application","chart":"mongodb-7.8.10","heritage":"Helm","release":"mongodb-application"},"name":"mongodb-application","namespace":"mongodb"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}}}}
    creationTimestamp: "2022-09-07T09:50:47Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: mongodb
      app.kubernetes.io/instance: mongodb-application
      chart: mongodb-7.8.10
      heritage: Helm
      release: mongodb-application
    name: mongodb-application
    namespace: mongodb
    resourceVersion: "6824"
    uid: 34854de8-762e-4607-aaea-0d18bd0a12e7
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
