apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mongodb","helm.sh/chart":"mongodb-13.1.2"},"name":"mongodb","namespace":"mongodb"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/name":"mongodb"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mongodb","helm.sh/chart":"mongodb-13.1.2"}},"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null,"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/name":"mongodb"}},"namespaces":["mongodb"],"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"env":[{"name":"BITNAMI_DEBUG","value":"false"},{"name":"MONGODB_ROOT_USER","value":"root"},{"name":"MONGODB_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb-root-password","name":"mongodb"}}},{"name":"ALLOW_EMPTY_PASSWORD","value":"no"},{"name":"MONGODB_SYSTEM_LOG_VERBOSITY","value":"0"},{"name":"MONGODB_DISABLE_SYSTEM_LOG","value":"no"},{"name":"MONGODB_DISABLE_JAVASCRIPT","value":"no"},{"name":"MONGODB_ENABLE_JOURNAL","value":"yes"},{"name":"MONGODB_PORT_NUMBER","value":"27017"},{"name":"MONGODB_ENABLE_IPV6","value":"no"},{"name":"MONGODB_ENABLE_DIRECTORY_PER_DB","value":"no"}],"image":"docker.io/bitnami/mongodb:6.0.1-debian-11-r1","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["/bitnami/scripts/ping-mongodb.sh"]},"failureThreshold":6,"initialDelaySeconds":30,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":10},"name":"mongodb","ports":[{"containerPort":27017,"name":"mongodb"}],"readinessProbe":{"exec":{"command":["/bitnami/scripts/readiness-probe.sh"]},"failureThreshold":6,"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{},"requests":{}},"securityContext":{"runAsNonRoot":true,"runAsUser":1001},"volumeMounts":[{"mountPath":"/bitnami/mongodb","name":"datadir","subPath":null},{"mountPath":"/bitnami/scripts","name":"common-scripts"}]}],"securityContext":{"fsGroup":1001,"sysctls":[]},"serviceAccountName":"mongodb","volumes":[{"configMap":{"defaultMode":360,"name":"mongodb-common-scripts"},"name":"common-scripts"},{"name":"datadir","persistentVolumeClaim":{"claimName":"mongodb"}}]}}}}
  creationTimestamp: "2022-09-07T06:29:44Z"
  generation: 1
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.1.2
  name: mongodb
  namespace: mongodb
  resourceVersion: "3570"
  uid: e9e3f2ea-2201-4a48-a769-0cba2d600a6f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
        helm.sh/chart: mongodb-13.1.2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: mongodb
                  app.kubernetes.io/instance: mongodb
                  app.kubernetes.io/name: mongodb
              namespaces:
              - mongodb
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MONGODB_ROOT_USER
          value: root
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DISABLE_JAVASCRIPT
          value: "no"
        - name: MONGODB_ENABLE_JOURNAL
          value: "yes"
        - name: MONGODB_PORT_NUMBER
          value: "27017"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        image: docker.io/bitnami/mongodb:6.0.1-debian-11-r1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bitnami/scripts/ping-mongodb.sh
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bitnami/scripts/readiness-probe.sh
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: datadir
        - mountPath: /bitnami/scripts
          name: common-scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: mongodb
      serviceAccountName: mongodb
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 360
          name: mongodb-common-scripts
        name: common-scripts
      - name: datadir
        persistentVolumeClaim:
          claimName: mongodb
status:
  conditions:
  - lastTransitionTime: "2022-09-07T06:29:51Z"
    lastUpdateTime: "2022-09-07T06:29:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-09-07T06:39:52Z"
    lastUpdateTime: "2022-09-07T06:39:52Z"
    message: ReplicaSet "mongodb-b79b9dd8d" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
