apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mongodb","helm.sh/chart":"mongodb-13.1.2"},"name":"mongodb","namespace":"mongodb"},"spec":{"ports":[{"name":"mongodb","nodePort":null,"port":27017,"targetPort":"mongodb"}],"selector":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/name":"mongodb"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2022-09-07T06:29:42Z"
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.1.2
  name: mongodb
  namespace: mongodb
  resourceVersion: "3374"
  uid: 197d91fe-3600-4337-b5fc-7bae12e45197
spec:
  clusterIP: 10.109.65.127
  clusterIPs:
  - 10.109.65.127
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
